services:
  krb5kdc:
    build:
      context: docker/kdc
    init: true
    volumes:
      - krb5:/etc/krb5
  zookeeper:
    build:
      context: docker/zookeeper
    init: true
    volumes:
      - zookeeper-data:/tmp/zookeeper
  hadoop1: &hadoop
    build:
      context: docker/hadoop
      args:
        HDFS_UID: ${UID}
        HDFS_GID: ${GID}
    init: true
    hostname: hadoop1
    privileged: true
    environment:
      KRB5_CONFIG: /etc/krb5/krb5.conf
    volumes:
      - krb5:/etc/krb5
      - ha-name-dir-shared:/var/lib/hadoop/ha-name-dir-shared
      - ./hadoop-etc:/opt/hadoop/etc/hadoop:ro
      - ./workspace:/home/hdfs/workspace
    working_dir: /home/hdfs/workspace
  hadoop2:
    <<: *hadoop
    hostname: hadoop2
  hadoop3:
    <<: *hadoop
    hostname: hadoop3
  hadoop4:
    <<: *hadoop
    hostname: hadoop4
  hadoop5:
    <<: *hadoop
    hostname: hadoop5
  hadoop6:
    <<: *hadoop
    hostname: hadoop6

volumes:
  zookeeper-data:
  krb5:
  ha-name-dir-shared: